version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: pgrkam
      POSTGRES_USER: pgrkam
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - events-service

  events-service:
    build: ./events-service
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  user-analytics:
    build: ./user-analytics
    ports:
      - "8002:8002"
    depends_on:
      - postgres

  ml-matching:
    build: ./ml-matching
    ports:
      - "8003:8003"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"   # Console UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  minio-data:
  pgdata:
